<a href="https://colab.research.google.com/github/bharatikasture573-cyber/Task13/blob/main/Task13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1.
import numpy as np
# a) Create a 1D array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Data Type:", arr1.dtype)

# b) Create a 3x3 2D array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print("2D Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [34]:
# 2.
import numpy as np

# a) 1D array of 8 zeros
arr1 = np.zeros(8)
print("a) 1D Array of 8 Zeros:",arr1)

# b) 4x4 array of ones
arr2 = np.ones((4, 4))
print("\nb) 4x4 Array of Ones:")
print(arr2)

# c) 3x3 matrix of zeros
arr3 = np.zeros((3, 3))
print("\nc) 3x3 Matrix of Zeros:")
print(arr3)

a) 1D Array of 8 Zeros: [0. 0. 0. 0. 0. 0. 0. 0.]

b) 4x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

c) 3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
# 3.
import numpy as np

# a) Numbers from 0 to 20
arr1 = np.arange(0,21)
print("Numbers From 0 to 20 : ",arr1)

# b) Even numbers from 10 to 50
arr2 = np.arange(10,51,2)
print("Even Numbers From 10 to 50 : ",arr2)

# c) Numbers from 5 to 100 with step of 5.
arr3 = np.arange(5,101,5)
print("Numbers from 5 to 100 with step of 5 : ",arr3)

Numbers From 0 to 20 :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Numbers From 10 to 50 :  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Numbers from 5 to 100 with step of 5 :  [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [41]:
# 4.
import numpy as np
# a) 10 equally spaced numbers between 0 and 5.
arr1 = np.linspace(0,5,10)
print("\n10 equally spaced numbers between 0 and 5 : ")
print(arr1)
print("Length:", len(arr1))

# b) 15 equally spaced numbers between 10 and 100
arr2 = np.linspace(10, 100, 15)
print("\n15 equally spaced numbers between 10 and 100 : ")
print(arr1)
print("Length:", len(arr2))


10 equally spaced numbers between 0 and 5 : 
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

15 equally spaced numbers between 10 and 100 : 
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 15


In [43]:
# 5.
import numpy as np

# a) 1D array of 10 random numbers between 0 and 1
arr1 = np.random.rand(10)
print(" 1D Array of 10 Random Numbers (0 to 1):",arr1)

# b) 3x3 matrix of random numbers from standard normal distribution
arr2 = np.random.randn(3, 3)
print("\n 3x3 Matrix (Standard Normal Distribution):")
print(arr2)

# c) 4x5 array of random integers between 10 and 50
arr3 = np.random.randint(10, 51, size=(4, 5))
print("\n 4x5 Matrix of Random Integers (10 to 50): ")
print(arr3)

 1D Array of 10 Random Numbers (0 to 1): [0.00494477 0.2141541  0.89604066 0.2972585  0.2299985  0.48010474
 0.37547165 0.62527224 0.97132549 0.54000103]

 3x3 Matrix (Standard Normal Distribution):
[[ 1.22021751  0.67350285 -1.29073971]
 [-0.34264914  0.28958249  0.60686173]
 [ 1.14186741  0.12817223  0.92359738]]

 4x5 Matrix of Random Integers (10 to 50): 
[[14 43 19 11 35]
 [12 34 36 27 10]
 [40 45 42 35 27]
 [27 25 20 41 38]]


In [45]:
# 6.
import numpy as np
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
print("Vector 1:", v1)
print("Vector 2:", v2)

addition = v1 + v2
print("\nAddition:")
print(addition)

subtraction = v1 - v2
print("\nSubtraction:")
print(subtraction)

multiplication = v1 * v2
dot_product = np.dot(v1, v2)
print("\nElement-wise Multiplication:")
print(multiplication)

print("\nDot Product:")
print(dot_product)

Vector 1: [2 4 6 8]
Vector 2: [1 3 5 7]

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100


In [46]:
# 7.
import numpy as np
# Create matrices
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
B = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])
print("Matrix A : ")
print(A)
print("\nMatrix B : ")
print(B)

addition = A + B
print("\nMatrix Addition:")
print(addition)

matrix_multiplication = A @ B
print("\nMatrix Multiplication:")
print(matrix_multiplication)

elementwise_multiplication = A * B
print("\nElement-wise Multiplication:")
print(elementwise_multiplication)

Matrix A : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B : 
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [47]:
# 8.
import numpy as np
arr = np.random.randint(1, 101, (4, 4))
print("4x4 Random Integer Matrix:")
print(arr)

# Print array properties
print("\nShape:", arr.shape)
print("Dimension (ndim):", arr.ndim)
print("Total Number of Elements (size):", arr.size)
print("Data Type:", arr.dtype)
print("Minimum Value:", arr.min())
print("Maximum Value:", arr.max())

4x4 Random Integer Matrix:
[[ 2 50 14 57]
 [47 11 85 63]
 [55 89 17 42]
 [38 63 48 96]]

Shape: (4, 4)
Dimension (ndim): 2
Total Number of Elements (size): 16
Data Type: int64
Minimum Value: 2
Maximum Value: 96


In [48]:
# 9.
import numpy as np
arr = np.random.randint(1, 51, 20)
matrix = arr.reshape(4, 5)
print("4x5 Matrix:")
print(matrix)

print("\nSum of all elements:", np.sum(matrix))
print("Mean of all elements:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

print("\nMaximum value in each row:")
print(np.max(matrix, axis=1))

4x5 Matrix:
[[49 50 50 44 30]
 [22 43 47 18 46]
 [42 37 38 50  9]
 [14 30 21 34 17]]

Sum of all elements: 691
Mean of all elements: 34.55
Standard Deviation: 13.200284087852049

Maximum value in each row:
[50 47 50 34]


In [50]:
# 10.
import numpy as np

try:
    # Ask the user how many random numbers to generate
    n = int(input("Enter the number of random numbers to generate: "))

    # Check if the number is positive
    if n <= 0:
        print("Error: Please enter a positive integer.")
    else:
        # Generate random integers between 10 and 100
        numbers = np.random.randint(10, 101, size=n)

        # Display the generated array
        print("\nGenerated Array:")
        print(numbers)

        # Display statistics
        print("\n******* Statistics ********")
        print("Mean               :", np.mean(numbers))
        print("Median             :", np.median(numbers))
        print("Standard Deviation :", np.std(numbers))
        print("Minimum Value      :", np.min(numbers))
        print("Maximum Value      :", np.max(numbers))

        # Reshape into a 2D array if possible
        print("\n**** Reshape ****")

        if n % 2 == 0:
            matrix = numbers.reshape(2, n // 2)

            print("Reshaped 2D Array:")
            print(matrix)

            # Calculate row-wise sum
            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))

        else:
            print("Cannot reshape into a 2D array because the number of elements is odd.")

except ValueError:
    print("Error: Please enter a valid integer.")

except Exception as e:
    print("An unexpected error occurred:", e)

Enter the number of random numbers to generate: 10

Generated Array:
[78 45 46 66 33 20 76 57 84 43]

******* Statistics ********
Mean               : 54.8
Median             : 51.5
Standard Deviation : 19.923855048659636
Minimum Value      : 20
Maximum Value      : 84

**** Reshape ****
Reshaped 2D Array:
[[78 45 46 66 33]
 [20 76 57 84 43]]

Row-wise Sum:
[268 280]
